# Generated by Django 3.2.7 on 2022-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires Datetime'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Datetime'),
        ),
    ]
