# Generated by Django 3.2.7 on 2022-06-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('featured', 'Featured')], max_length=50, verbose_name='Type'),
        ),
    ]
